# Generated by Django 3.2.7 on 2021-09-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kuerzel', models.CharField(max_length=3)),
                ('kn_nr', models.CharField(max_length=5)),
                ('beschreibung', models.CharField(max_length=300)),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
    ]
